# Generated by Django 5.0.6 on 2024-05-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0002_alter_customerorder_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='created_date',
            field=models.DateField(),
        ),
    ]
