# Generated by Django 5.0.6 on 2024-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0003_alter_customerorder_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='black', max_length=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.FloatField(default=1.0),
        ),
    ]
